package com.kull.android;

public class Const {

	
	private Const() {
    }

	public enum LogLevel{
		error,none,waring,info
	}
	


    /**
     * Set this flag to GD_LOG_LEVEL_NONE when releasing your application in
     * order to remove all logs generated by GreenDroid.
     */
    private static final LogLevel LOG_LEVEL = LogLevel.none;

    /**
     * Indicates whether info logs are enabled. This should be true only when
     * developing/debugging an application/the library
     */
    public static final boolean INFO_LOGS_ENABLED = (LOG_LEVEL == LogLevel.info);

    /**
     * Indicates whether warning logs are enabled
     */
    public static final boolean WARNING_LOGS_ENABLED = INFO_LOGS_ENABLED || (LOG_LEVEL == LogLevel.waring);

    /**
     * Indicates whether error logs are enabled. Error logs are usually always
     * enabled, even in production releases.
     */
    public static final boolean ERROR_LOGS_ENABLED = WARNING_LOGS_ENABLED || (LOG_LEVEL == LogLevel.error);

}
